update-user
ToKoSoftware/dhbw-sonnenstrahl pull request #15
Opened 2020-11-27 10:20 UTC by LisaFremdt

added update-user and the respective put-code in server.ts BUT wrong …error when der is an invalid email in body

2020-11-27 12:56 UTC, DominikRuf commented
@LisaFremdt änderst du update-order bitte auch noch.

2020-12-01 08:59 UTC, LisaFremdt commented on server/src/api/v1/customers/update-customer.ts
>          return res.send(wrapResponse(false, { error: "Fields must not be empty" }));
hierfehlt galub auch der fehlerstatus oder nicht?

2020-12-01 09:18 UTC, DominikRuf requested changes
Siehe Kommentare

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +    //Customer Objekt from database must not be null, id must not be changed and all set keys mut not be empty.
```suggestion
    //User Objekt from database must not be null, id must not be changed and all set keys mut not be empty.
```

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +
Hier fehlt ein check, ob die mitgegebene customerId, denn überhaupt zu einem Customer passt, falls sie gesetzt ist.

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +    if (user !== null && (req.body.id === undefined || req.params.id === req.body.id) && checkKeysAreNotEmptyOrNotSet(mappedIncomingData, requiredFields) !== false && validEmail !== false ) {
Aktuell darf man is_admin setzen.
Absicht? 
Ich würde eher sagen, dass wir is_admin nicht ändern lassen wollen.

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +        if (!success) {
Der Fehler wird auch geworfen, wenn ein Datentyp nicht richtig ist (UUID des Customers z.B.). Wenn das oben aber gecheckt wird, ob der Customer überhaupt ein customer ist, sollte das passen.

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +    let validEmail = EmailValidator.validate(mappedIncomingData.email);
```suggestion
    let validEmail = EmailValidator.validate(mappedIncomingData.email) || isBlank(mappedIncomingData.email)
```

2020-12-01 09:18 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +    let validEmail = EmailValidator.validate(mappedIncomingData.email);
problem hier: Wenn die Mail erst garnicht gesetzt ist, dann ist das immer false, als wenn die Mail nicht dem Format entsprechen würde.

2020-12-01 09:22 UTC, DominikRuf commented on server/src/api/v1/customers/update-customer.ts
>          return res.send(wrapResponse(false, { error: "Fields must not be empty" }));
Ja, richtig. Habe ich sogar übersehen.
Den kannst du dann auch gleich noch mit reinhauen.

2020-12-01 12:03 UTC, DominikRuf requested changes
siehe weitere kommentare

2020-12-01 12:03 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +    let customer: Customer | null;
Wenn du hier den customer explizit mit type Customer | null angibst, dann meckert er unten in Zeile 62, da du customer ja ggf nicht setzt, wenn es nicht in die If-Bedingung in Zeile 43 reinspringt.

2020-12-01 12:09 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +
customer === null wird abgefangen. Habe ich unten übersehen.
Aber das andere musst noch machen.

2020-12-01 12:15 UTC, DominikRuf commented on server/src/api/v1/users/update-user.ts
> +
blindes ich... Auch success wird abgefangen ne Zeile drunter. passt.

2020-12-01 13:50 UTC, TomasKostadinov requested changes

2020-12-01 13:50 UTC, TomasKostadinov commented on server/src/api/v1/users/update-user.ts
> +    let updateResult;
Type?

2020-12-01 13:50 UTC, TomasKostadinov commented on server/src/api/v1/users/update-user.ts
> +    //User Objekt from database must not be null, id must not be changed and all set keys mut not be empty.
```suggestion
    //User object from database must not be null, id must not be changed and all set keys mut not be empty.
```

2020-12-01 15:20 UTC, TomasKostadinov approved these changes
Testing mache ich im Zuge der Frontend-Implementierung 👍🏽

2020-12-01 15:25 UTC, DominikRuf approved these changes

2020-12-01 15:34 UTC, merged