Backend admin stats and exports
ToKoSoftware/dhbw-sonnenstrahl pull request #25
Opened 2020-12-05 14:00 UTC by DominikRuf

2020-12-06 11:15 UTC, DominikRuf commented
@TomasKostadinov schau mal bitte, ob dir das so genügt.
![MonthlyStats](https://user-images.githubusercontent.com/56634563/101278602-ac5baa80-37bc-11eb-9052-d207cbcca068.png)

2020-12-06 11:47 UTC, TomasKostadinov commented
Das sieht doch schonmal super aus!

2020-12-06 11:47 UTC, TomasKostadinov commented
Ich werde es später testen und reviewen

2020-12-07 20:05 UTC, TomasKostadinov requested changes

2020-12-07 20:05 UTC, TomasKostadinov commented on server/src/api/v1/admin/get-monthly-stats.ts
> +async function countMonthlyEntities(model: typeof User | typeof Customer | typeof Plan | typeof Order) {
Schöner für die Lesbarkeit wäre
```suggestion
async function countMonthlyEntities(model: monthlyEntityType) {
```
und weiter unten
```ts
export type monthlyEntityType = typeof User | typeof Customer | typeof Plan | typeof Order;
```

2020-12-07 20:05 UTC, TomasKostadinov commented on server/src/api/v1/admin/get-stats.ts
> +
Die könnte man bestimmt alle parallel ausführen, da muss ich mal am Ende mit der Performance schauen, wie die ist. 

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2020-12-07 20:05 UTC, TomasKostadinov commented on server/src/api/v1/admin/get-stats.ts
> +
Erstmal ignorieren

2020-12-07 22:22 UTC, TomasKostadinov commented
@DominikRuf 
Kannst du noch eine Route hinzufügen, eine, die mir folgendes zurück gibt:

```js
data: {
   "check24": 23, // count 
   "anderer": 23,
   "referrer": 23,
}
```

Also sozusagen eine Aufschlüsselung der Anzahl nach Referrer. 

SQL Abfrage wäre ja:
```sql
SELECT DISTINCT referrer from "Orders";
```
Ich glaube Sequelize kann das auch:
https://stackoverflow.com/questions/12156206/sequelize-select-distinct-rows/30070249

2020-12-08 18:35 UTC, DominikRuf commented
> @DominikRuf
> Kannst du noch eine Route hinzufügen, die mir folgendes zurück gibt:
> 
> ```js
> data: {
>    "check24": 23, // count 
>    "anderer": 23,
>    "referrer": 23,
> }
> ```
> 
> Also sozusagen eine Aufschlüsselung der Anzahl nach Referrer.
> 
> SQL Abfrage wäre ja:
> 
> ```sql
> SELECT DISTINCT referrer from "Orders";
> ```
> 
> Ich glaube Sequelize kann das auch:
> https://stackoverflow.com/questions/12156206/sequelize-select-distinct-rows/30070249

done mit Commit 868cda9

2020-12-08 18:47 UTC, TomasKostadinov requested changes

2020-12-08 18:47 UTC, TomasKostadinov commented on server/src/api/v1/admin/export-users.ts
> +        return res.status(404).send(wrapResponse(false, { error: 'No active order found' }));
```suggestion
        return res.status(404).send(wrapResponse(false, { error: 'No users found' }));
```

2020-12-08 18:47 UTC, TomasKostadinov commented on server/src/api/v1/admin/get-referrer-stats.ts
> +        return res.status(404).send(wrapResponse(false, { error: 'No refferrer found' }));
```suggestion
        return res.status(404).send(wrapResponse(false, { error: 'No refferrer found' }));
```
Kannst du in diesem Fall nicht ein leeres [] zurück geben? Ist ja ansich kein Fehler

2020-12-08 18:48 UTC, TomasKostadinov commented
Testing mache ich, wenn ich das in den Admin einbaue

2020-12-08 19:15 UTC, TomasKostadinov approved these changes

2020-12-08 19:21 UTC, merged