Frontend Login & Registration
ToKoSoftware/dhbw-sonnenstrahl pull request #28
Opened 2020-12-07 22:32 UTC by TomasKostadinov

- Frontend Login & Registration
- Admin bearbeiten von Usern, Kunden, Bestellungen

2020-12-07 22:34 UTC, TomasKostadinov commented
Fehlt zu Completion von diesem PR:
* Test vom Update-Order (Serverseitiger Bug)

2020-12-08 18:12 UTC, DominikRuf requested changes
Siehe Kommentare, etc.

2020-12-08 18:12 UTC, DominikRuf commented on frontend/src/app/admin/customers/customers.component.html
> +  <input class="mt-4 form-input block w-full rounded-md sm:leading-5" type="email" placeholder="Email" [(ngModel)]="currentEditCustomer.city">
type="email" ?

2020-12-08 18:12 UTC, DominikRuf commented on frontend/src/app/admin/orders/order-row/order-row.component.html
> +  <input class="mt-4 form-input block w-full rounded-md sm:leading-5" type="email" placeholder="Email" [(ngModel)]="currentEditOrder.referrer">
type und placeholer?

2020-12-08 18:12 UTC, DominikRuf commented on frontend/src/app/icons/icons.module.ts
> +  Key, MousePointer
```suggestion
  Key, 
  MousePointer
```

2020-12-08 18:12 UTC, DominikRuf commented on frontend/src/app/interfaces/customer.interface.ts
> +}
hier fehlt die userId.

2020-12-08 18:12 UTC, DominikRuf commented on frontend/src/app/login-register/register/register.component.html
> +                       placeholder="Passwort"/>
type und placeholder.

2020-12-08 18:32 UTC, TomasKostadinov commented on frontend/src/app/admin/customers/customers.component.html
> +  <input class="mt-4 form-input block w-full rounded-md sm:leading-5" type="email" placeholder="Email" [(ngModel)]="currentEditCustomer.city">
Danke

2020-12-08 18:32 UTC, TomasKostadinov commented on frontend/src/app/admin/orders/order-row/order-row.component.html
> +  <input class="mt-4 form-input block w-full rounded-md sm:leading-5" type="email" placeholder="Email" [(ngModel)]="currentEditOrder.referrer">
Fixed

2020-12-08 18:34 UTC, TomasKostadinov commented on frontend/src/app/login-register/register/register.component.html
> +                       placeholder="Passwort"/>
Type ist richtig, oder?

2020-12-08 18:40 UTC, DominikRuf commented on frontend/src/app/login-register/register/register.component.html
> +                       placeholder="Passwort"/>
Sry war das aria-label mal wieder.
War so im type und placeholder flow :D

2020-12-08 18:40 UTC, DominikRuf commented on frontend/src/app/login-register/register/register.component.html
> +                       placeholder="Passwort"/>
Sry klar nicht type und placeholder, sondern mein beliebtes aria-label, jetzt wo ich weiß, was es bedeutet/wofür es da ist ;)

2020-12-08 18:42 UTC, TomasKostadinov commented on frontend/src/app/login-register/register/register.component.html
> +                       placeholder="Passwort"/>
Gut, das hab ich rausgeschmissen - wir müssten das sonst an 2000 Stellen einfügen. Also falls wir das mal verkaufen sollten daran denken haha 😅

2020-12-08 18:44 UTC, DominikRuf approved these changes
:+1:

2020-12-08 19:15 UTC, merged