added bcryptjs and changed login and create user
ToKoSoftware/dhbw-sonnenstrahl pull request #29
Opened 2020-12-09 23:19 UTC by LisaFremdt

2020-12-10 08:39 UTC, TomasKostadinov requested changes

2020-12-10 08:39 UTC, TomasKostadinov commented on server/src/api/v1/users/auth-user.ts
> +    const bcrypt = require ('bcryptjs');
Bitte, so wie alle anderen Imports auch, das richtig einbinden mit `import,` nicht `require`

2020-12-10 08:39 UTC, TomasKostadinov commented on server/src/api/v1/users/auth-user.ts
> +                //password: incomingData.password
Rückgängig machen, sende einfach das gehashte passwort in die Datenbankabfrage, wenn es stimmt, dann kannst du das auf db Ebene machen und musst nichts mehr ändern

2020-12-10 08:39 UTC, TomasKostadinov commented on server/src/api/v1/users/auth-user.ts
> +        bcrypt.compare(req.body.password, user.password).then((isMatch: any) => {if (!isMatch) return res.status(400).send(wrapResponse(false, { error: 'Unauthorized!' }))});
s.o.

2020-12-10 08:39 UTC, TomasKostadinov commented on server/src/api/v1/users/create-user.ts
> +    const bcrypt = require ('bcryptjs');
s.o.

2020-12-10 08:39 UTC, TomasKostadinov commented on server/src/api/v1/users/create-user.ts
> +    req.body.password = hashedPassword;
Warum?

2020-12-10 12:10 UTC, TomasKostadinov requested changes

2020-12-10 12:10 UTC, TomasKostadinov commented on server/src/functions/map-users.func.ts
> +    incomingData.password = hashedPassword;
Aufräumen

2020-12-10 12:10 UTC, TomasKostadinov commented on server/src/interfaces/users.interface.ts
> +import { Hash } from "crypto";
Nicht notwendig

2020-12-12 15:43 UTC, DominikRuf requested changes

2020-12-12 15:43 UTC, DominikRuf commented on server/src/server.ts
> +    app.get('/api/v1/users',/*userIsAuthorized, userIsAdmin,*/ (req, res) => getUsers(req, res));
Bitte hier wieder einkommentieren.

2020-12-12 15:43 UTC, DominikRuf commented on server/src/api/v1/users/auth-user.ts
> +                password: mappedIncomingData.password
Das wird doch nicht funktionieren, weil der hash doch nicht stimmt, oder?

2020-12-12 18:30 UTC, TomasKostadinov commented on server/src/api/v1/users/auth-user.ts
> +                password: mappedIncomingData.password
Jo stimmt

2020-12-12 18:31 UTC, TomasKostadinov commented on server/src/server.ts
> +    app.get('/api/v1/users',/*userIsAuthorized, userIsAdmin,*/ (req, res) => getUsers(req, res));
Git blame sagt ich bin unschuldig! 😅
Ja mach ich, hab ich übersehen

2020-12-13 11:05 UTC, DominikRuf approved these changes

2020-12-13 11:07 UTC, DominikRuf submitted a review, later dismissed

2020-12-13 19:14 UTC, merged