Documenation update of postman collection
ToKoSoftware/dhbw-sonnenstrahl pull request #44
Opened 2020-12-22 10:39 UTC by DominikRuf

…lanations

2020-12-30 15:17 UTC, TomasKostadinov requested changes
Admin Statistik Routen Fehlen

2020-12-30 15:20 UTC, TomasKostadinov commented
Evtl. als default beim login gleich die sabrina wassertal eintragen (welche unser standart admin ist)

2020-12-30 15:58 UTC, DominikRuf commented
Ja, wollte jetzt den Seeder abwarten dass das alles läuft.
Gehe morgen nochmal drüber und mach das fertig :)

2021-01-03 11:50 UTC, TomasKostadinov approved these changes

2021-01-03 11:50 UTC, merged