Calculator improvements
ToKoSoftware/dhbw-sonnenstrahl pull request #57
Opened 2021-01-25 18:59 UTC by TomasKostadinov

2021-01-26 16:11 UTC, TomasKostadinov commented on frontend/src/app/ui/modals/confirm-modal/confirm-modal.component.ts
> +   * run confirmation
Emit confirm action event

2021-01-26 16:11 UTC, TomasKostadinov commented on frontend/src/app/ui/modals/confirm-modal/confirm-modal.component.ts
> +   * run cancelation
Emit cancel action event

2021-01-26 16:12 UTC, TomasKostadinov commented on frontend/src/app/ui/modals/modal/modal.component.ts
> +   * closes modal, if not blocked
Blocking bedeutet, dass man es nicht schließen darf

Close modal if user is allowed to

2021-01-26 16:12 UTC, TomasKostadinov commented on frontend/src/app/ui/navbar/navbar.component.ts
> +   * toggle navigation bar
toggle navigation bar status

2021-01-26 16:13 UTC, TomasKostadinov commented on frontend/src/app/ui/navbar/navbar.component.ts
> +   * search plan
Wird ja keine Suche ausgeführt, sondern nur auf die Seite weitergeleitet

Redirect to search overview page

2021-01-29 21:49 UTC, DominikRuf requested changes

2021-01-29 21:49 UTC, DominikRuf commented on frontend/src/app/admin/plans/plans.component.ts
> +   */
```suggestion
   * @param plan the plan that should be deleted
   */
```

2021-01-29 21:49 UTC, DominikRuf commented on frontend/src/app/login-register/register/register.component.ts
> +   * Create a user and generate a jwt with the same credentials
```suggestion
   * Create an user and generate a jwt with the same credentials
```

2021-01-29 21:49 UTC, DominikRuf commented on frontend/src/app/my-profile/my-orders/order-detail/order-detail.component.ts
> +   * Terminate a order
```suggestion
   * Terminate an order
```

2021-01-29 21:49 UTC, DominikRuf commented on frontend/src/app/services/login/login.service.ts
> +   * Remove JWT from loacl storage and reload JWT
```suggestion
   * Remove JWT from local storage and reload JWT
```

2021-01-30 13:55 UTC, DominikRuf submitted a review, later dismissed

2021-01-30 14:01 UTC, DominikRuf approved these changes

2021-01-30 14:01 UTC, merged