Add Database Seeders
ToKoSoftware/dhbw-sonnenstrahl pull request #7
Opened 2020-11-22 19:44 UTC by TomasKostadinov

Database Seeders will be run after the database migrations to provide an working admin example

- [x] Create Admin user

- [x] Add 100 fake users

- [x] Add 100 fake orders

- [x] Import demo plan csv 

- [ ] Run on initial docker setup

- [ ] Provide documentation

2020-12-18 08:23 UTC, DominikRuf requested changes
Allgemein:
Bitte bei den Datumsangaben drauf achten, dass unterschiedliches verwendet wird, dass das in den Stats (Admin Bereich, wofür wir ja diese Seeder auch machen) verschiedenes haben.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201122190024-demo-admin-user.js
> +            password: 'qwertz123',
wird so nicht funktionieren mit dem Login dann!
Hashing nicht vergessen!

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201122190212-demo-users.js
> +                password: faker.internet.password(),
Hashing auch hier nicht vergessen.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201122190212-demo-users.js
> +        for (let i = 0; i <= 200; i++) {
201 durchläufe

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +        for (let i = 0; i <= 200; i++) {
201 Durchläufe.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                password: faker.internet.password(),
Hashing

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +            for (let i = 0; i <= 200; i++) {
201 Durchläufe.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +            for (let i = 0; i <= 50; i++) {
51 Durchläufe.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +            for (let i = 0; i <= 250; i++) {
251 Durchläufe.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    referrer: 'SEEDER',
für die Stats nachher wäre es schöner wenn hier auch Zufallswerte verarbeitet werden würden.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    referrer: 'SEEDER',
s.o.

2020-12-18 08:23 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    terminatedAt: new Date(),
terminatedAt sollte eigentlich nach createdAt und gleichzeitig mit updatedAt liegen.

2020-12-18 09:00 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    terminatedAt: new Date(),
Oder halt nicht gesetzt sein -> Sollen ja nicht alle gekündigt werden

2020-12-18 09:49 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    terminatedAt: new Date(),
ist nicht bei allen ;) Also das hat Sie schon richtig gemacht.

2020-12-21 14:11 UTC, DominikRuf commented
@LisaFremdt unbedingt einmal pullen bevor du weitermachst.
Habe grade den Main reingemerged, dass das gefixte Zeug auch in deinem Stand drin ist.

2020-12-23 10:40 UTC, DominikRuf requested changes
Datumsproblem jetzt gut gelöst :+1:

2020-12-23 10:40 UTC, DominikRuf commented on server/package.json
> +    "FileReader": "^0.10.2",
bitte wieder deinstallieren.

2020-12-23 10:40 UTC, DominikRuf commented on server/package.json
> +    "buffer-concat": "^1.0.0",
bitte wieder deinstallieren.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/api/v1/plans/import-plan.ts
> +export async function loadCSV(file: UploadedFile): Promise<FileUploadPlan[]> {
export wieder weg. Wird nirgends sonst verwendet.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/api/v1/plans/import-plan.ts
> +export function createPlanEntry(data: InternalPlan) {
export wieder weg. Wird nirgends sonst verwendet.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201122190024-demo-admin-user.js
> +}
duplicate code.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201122190212-demo-users.js
> +};
duplicate code.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +}
duplicate code.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    planId: plans[getRandomInt(384)].id,
nicht gut! 
So passen postcode vom customer und postcode vom plan nur zufällig zueinander.
Für Faker-Daten eigentlich egal, aber aus Konsistenzgründen ungut!

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    planId: plans[getRandomInt(384)].id,
s.o.

2020-12-23 10:40 UTC, DominikRuf commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    planId: plans[getRandomInt(384)].id,
s.o.

2020-12-23 14:00 UTC, TomasKostadinov reviewed
Bitte vorallem for csv löschen

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +            const u = randomTime(new Date("01-01-2020 10:30"), new Date("12-31-2020 02:10"));
Bitte Relativ machen - Bsp heutiges Datum, vor einem Jahr & heutiges Datum
-> So wird vermieden, dass du z.B. Sachen in der Zukunft anlegst

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                updatedAt: randomTime(new Date(u), new Date("12-31-2020 02:10"))
s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    updatedAt: randomTime(new Date(users[i].createdAt), new Date("12-31-2020 02:10")),
s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +        let customers =[];
formattierung

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                const c = randomTime(new Date(users[i].createdAt), new Date("12-31-2020 02:10"));
s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    updatedAt: randomTime(new Date(c), new Date("12-31-2020 02:10")),
s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                const o =  randomTime(new Date(customers[i].createdAt), new Date("12-31-2020 02:10"));
- Formattierung
- Datum s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-cutomers-orders.js
> +                    updatedAt: randomTime(new Date(o), new Date("12-31-2020 02:10")),
s.o.

2020-12-23 14:34 UTC, TomasKostadinov commented on server/src/seeders/20201122190212-demo-users.js
> +    var diff =  end.getTime() - start.getTime();
Formattierung

2020-12-23 18:29 UTC, DominikRuf submitted a review, later dismissed

2020-12-23 18:31 UTC, LisaFremdt commented
@TomasKostadinov please review.

2020-12-23 20:08 UTC, TomasKostadinov reviewed
Restliche Kosmetik - Testing mach ich gleich

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +                        updatedAt: timeFunc.randomTime(c, timeFunc.endTime),
```suggestion
                        createdAt: date,
                        updatedAt: timeFunc.randomTime(date, timeFunc.endTime),
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +                    const ou = timeFunc.randomTime(o, timeFunc.endTime);
sinnvoll benennen

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +                for (let i = 0; i <= 64; i++) {
```suggestion
                for (let i = 0; i < 65; i++) {
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +                    const o =  timeFunc.randomTime(customers[i].createdAt, timeFunc.endTime);
```suggestion
                    const date =  timeFunc.randomTime(customers[i].createdAt, timeFunc.endTime);
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +                        updatedAt: timeFunc.randomTime(o, timeFunc.endTime),
```suggestion
                        createdAt: date,
                        updatedAt: timeFunc.randomTime(date, timeFunc.endTime),
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201217175111-demo-customers-and-orders.js
> +const v4 = require("uuid").v4;
```suggestion
const v4 = require('uuid').v4;
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201122190212-demo-users.js
> +const v4 = require("uuid").v4;
```suggestion
const v4 = require('uuid').v4;
```

2020-12-23 20:08 UTC, TomasKostadinov commented on server/src/seeders/20201122190024-demo-admin-user.js
> +const v4 = require("uuid").v4;
```suggestion
const v4 = require('uuid').v4;
```

2020-12-23 20:20 UTC, TomasKostadinov commented
Testing hat geklappt - super Arbeit!

2020-12-24 12:30 UTC, merged